# Generated by Django 5.2.6 on 2025-09-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='logo',
            field=models.ImageField(blank=True, help_text='Company logo (will be resized to 200x200px)', null=True, upload_to='employer_logos/'),
        ),
    ]
