# Generated by Django 5.2.6 on 2025-09-18 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EORClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('company_name', models.CharField(max_length=255)),
                ('registration_code', models.CharField(max_length=100)),
                ('contact_person_name', models.CharField(max_length=200)),
                ('contact_person_email', models.EmailField(max_length=254)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EORAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('agreement_type', models.CharField(max_length=50)),
                ('terms_and_conditions', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('signed_document', models.FileField(blank=True, null=True, upload_to='eor_agreements/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_SIGNATURE', 'Pending Signature'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20)),
                ('eor_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eor_agreements', to='eor_services.eorclientprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EORPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('job_title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eor_placements', to='employees.employeeprofile')),
                ('employment_contract', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eor_placement', to='core.contract')),
                ('eor_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='eor_services.eoragreement')),
                ('eor_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eor_placements', to='eor_services.eorclientprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('period_start_date', models.DateField()),
                ('period_end_date', models.DateField()),
                ('run_date', models.DateTimeField(auto_now_add=True)),
                ('total_gross_payout', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_net_payout', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_taxes', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSED', 'Processed'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='DRAFT', max_length=20)),
                ('xml_export_file', models.FileField(blank=True, null=True, upload_to='payroll_exports/')),
                ('eor_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='eor_services.eorclientprofile')),
                ('generated_payslips', models.ManyToManyField(blank=True, related_name='payroll_runs', to='employees.payslip')),
            ],
            options={
                'unique_together': {('eor_client', 'period_start_date', 'period_end_date')},
            },
        ),
    ]
