# Generated by Django 5.2.6 on 2025-09-18 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('employers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='employers.assignment'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='employees.employeeprofile'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_timesheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='employees.employeeprofile'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='employers.assignment'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='employees.employeeprofile'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='work_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.workschedule'),
        ),
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together={('employee', 'period_start_date', 'period_end_date')},
        ),
        migrations.AlterUniqueTogether(
            name='workschedule',
            unique_together={('employee', 'date', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='timesheet',
            unique_together={('employee', 'date')},
        ),
    ]
