# Generated by Django 5.2.6 on 2025-09-24 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
        ('employers', '0003_alter_assignment_options_assignment_actual_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payslip',
            options={'ordering': ['-period_start_date']},
        ),
        migrations.AlterModelOptions(
            name='timesheet',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='workschedule',
            options={'ordering': ['-date', '-start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together={('employee', 'assignment', 'period_start_date', 'period_end_date')},
        ),
        migrations.AlterUniqueTogether(
            name='timesheet',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='workschedule',
            unique_together={('employee', 'assignment', 'date', 'start_time')},
        ),
        migrations.AddField(
            model_name='payslip',
            name='base_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='bonuses_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='payslip',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='overtime_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='pay_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('SENT', 'Sent to Employee'), ('VIEWED', 'Viewed by Employee')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='payslip',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='actual_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='actual_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='employers.assignment'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='break_duration',
            field=models.IntegerField(default=0, help_text='Break duration in minutes'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='job_position',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='payslips/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RESUBMIT', 'Needs Resubmission')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='work_schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timesheet', to='employees.workschedule'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled'), ('NO_SHOW', 'No Show')], default='PLANNED', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='timesheet',
            unique_together={('employee', 'assignment', 'date')},
        ),
    ]
