# Generated by Django 5.2.6 on 2025-09-25 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_payslip_options_alter_timesheet_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.TextField(help_text='Describe your educational background', verbose_name='Education')),
                ('experience', models.TextField(help_text='Describe your work experience', verbose_name='Work Experience')),
                ('skills', models.TextField(help_text='List your professional skills', verbose_name='Skills')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('place_of_birth', models.CharField(blank=True, max_length=255, verbose_name='Place of Birth')),
                ('place_of_residence', models.CharField(blank=True, max_length=255, verbose_name='Place of Residence')),
                ('contacts', models.CharField(blank=True, max_length=255, verbose_name='Emergency Contacts')),
                ('languages', models.TextField(blank=True, help_text='Languages you speak and proficiency level', verbose_name='Languages')),
                ('civil_status', models.CharField(blank=True, max_length=100, verbose_name='Civil Status')),
                ('professional_experience', models.TextField(blank=True, help_text='Detailed professional experience', verbose_name='Professional Experience')),
                ('other_relevant_information', models.TextField(blank=True, verbose_name='Other Relevant Information')),
                ('characteristics', models.TextField(blank=True, verbose_name='Personal Characteristics')),
                ('hobby', models.TextField(blank=True, verbose_name='Hobbies & Interests')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='cv_attachments/', verbose_name='CV Attachment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cv', to='employees.employeeprofile')),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CVs',
            },
        ),
    ]
