# Generated by Django 5.2.6 on 2025-09-18 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='application_date',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='posted_date',
        ),
    ]
